spring:
    cloud:
        function:
            definition: identity;reverse;uppercase;uppercase|reverse
        stream:
            default:
                content-type: application/*+avro
            function:
                bindings:
                    uppercase|reverse-in-0: upperCaseReverseInput
            kafka:
                binder:
                    producer-properties:
                        schema.registry.url: "http://localhost:8081"
    datasource:
        password: test
        url: jdbc:postgresql://localhost:5432/postgres
        username: message
    jpa:
        hibernate:
            ddl-auto: create
    kafka:
        bootstrapServers: PLAINTEXT://localhost:9092




